_base_: ['./default.yaml']

# 只修改数据路径
data:
  train:
    dataset:
      ann_file: '/mnt/bevfusion_mit_xmy/xmy_tools/tyjt2pkl/step3_1_output/tyjt_infos_train.pkl'
    type: 'NuScenesDataset'  # 直接使用NuScenesDataset，不用CBGSDataset包装
  val:
    ann_file: '/mnt/bevfusion_mit_xmy/xmy_tools/tyjt2pkl/step3_1_output/tyjt_infos_val.pkl'
