import torch
ckpt = torch.load('pretrained/camera-only-det.pth')
state_dict = ckpt['state_dict']

# 查看所有键的结构
print('=== 完整的键结构（前100个）===')
for i, key in enumerate(list(state_dict.keys())):
    if i < 100:
        shape = state_dict[key].shape
        print(f'{i:3d}: {key:60s} {str(shape):20s}')
        
    # 特别关注一些关键层
    if 'encoders.camera.vtransform' in key:
        print(f'  [LSSTransform] {key}: {shape}')
    elif 'heads.object' in key and 'weight' in key:
        print(f'  [CenterHead] {key}: {shape}')
        
    if i >= 100:
        print('... (只显示前100个)')
        break


"""
"
0: encoders.camera.backbone.patch_embed.projection.weight
1: encoders.camera.backbone.patch_embed.projection.bias
2: encoders.camera.backbone.patch_embed.norm.weight
3: encoders.camera.backbone.patch_embed.norm.bias
4: encoders.camera.backbone.stages.0.blocks.0.norm1.weight
5: encoders.camera.backbone.stages.0.blocks.0.norm1.bias
6: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table
7: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.relative_position_index
8: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.qkv.weight
9: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.qkv.bias
10: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.proj.weight
11: encoders.camera.backbone.stages.0.blocks.0.attn.w_msa.proj.bias
12: encoders.camera.backbone.stages.0.blocks.0.norm2.weight
13: encoders.camera.backbone.stages.0.blocks.0.norm2.bias
14: encoders.camera.backbone.stages.0.blocks.0.ffn.layers.0.0.weight
15: encoders.camera.backbone.stages.0.blocks.0.ffn.layers.0.0.bias
16: encoders.camera.backbone.stages.0.blocks.0.ffn.layers.1.weight
17: encoders.camera.backbone.stages.0.blocks.0.ffn.layers.1.bias
18: encoders.camera.backbone.stages.0.blocks.1.norm1.weight
19: encoders.camera.backbone.stages.0.blocks.1.norm1.bias

=== 查找head相关参数 ===
heads.object.shared_conv.conv.weight: torch.Size([64, 256, 3, 3])
heads.object.shared_conv.bn.weight: torch.Size([64])
heads.object.shared_conv.bn.bias: torch.Size([64])
heads.object.shared_conv.bn.running_mean: torch.Size([64])
heads.object.shared_conv.bn.running_var: torch.Size([64])
heads.object.shared_conv.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.0.reg.1.bias: torch.Size([2])
heads.object.task_heads.0.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.0.height.1.bias: torch.Size([1])
heads.object.task_heads.0.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.0.dim.1.bias: torch.Size([3])
heads.object.task_heads.0.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.0.rot.1.bias: torch.Size([2])
heads.object.task_heads.0.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.0.vel.1.bias: torch.Size([2])
heads.object.task_heads.0.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.0.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.0.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.0.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.0.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.0.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.0.heatmap.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.0.heatmap.1.bias: torch.Size([1])
heads.object.task_heads.1.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.1.reg.1.bias: torch.Size([2])
heads.object.task_heads.1.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.1.height.1.bias: torch.Size([1])
heads.object.task_heads.1.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.1.dim.1.bias: torch.Size([3])
heads.object.task_heads.1.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.1.rot.1.bias: torch.Size([2])
heads.object.task_heads.1.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.1.vel.1.bias: torch.Size([2])
heads.object.task_heads.1.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.1.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.1.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.1.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.1.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.1.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.1.heatmap.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.1.heatmap.1.bias: torch.Size([2])
heads.object.task_heads.2.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.2.reg.1.bias: torch.Size([2])
heads.object.task_heads.2.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.2.height.1.bias: torch.Size([1])
heads.object.task_heads.2.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.2.dim.1.bias: torch.Size([3])
heads.object.task_heads.2.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.2.rot.1.bias: torch.Size([2])
heads.object.task_heads.2.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.2.vel.1.bias: torch.Size([2])
heads.object.task_heads.2.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.2.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.2.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.2.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.2.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.2.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.2.heatmap.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.2.heatmap.1.bias: torch.Size([2])
heads.object.task_heads.3.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.3.reg.1.bias: torch.Size([2])
heads.object.task_heads.3.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.3.height.1.bias: torch.Size([1])
heads.object.task_heads.3.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.3.dim.1.bias: torch.Size([3])
heads.object.task_heads.3.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.3.rot.1.bias: torch.Size([2])
heads.object.task_heads.3.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.3.vel.1.bias: torch.Size([2])
heads.object.task_heads.3.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.3.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.3.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.3.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.3.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.3.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.3.heatmap.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.3.heatmap.1.bias: torch.Size([1])
heads.object.task_heads.4.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.4.reg.1.bias: torch.Size([2])
heads.object.task_heads.4.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.4.height.1.bias: torch.Size([1])
heads.object.task_heads.4.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.4.dim.1.bias: torch.Size([3])
heads.object.task_heads.4.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.4.rot.1.bias: torch.Size([2])
heads.object.task_heads.4.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.4.vel.1.bias: torch.Size([2])
heads.object.task_heads.4.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.4.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.4.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.4.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.4.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.4.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.4.heatmap.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.4.heatmap.1.bias: torch.Size([2])
heads.object.task_heads.5.reg.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.reg.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.reg.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.reg.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.reg.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.reg.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.reg.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.5.reg.1.bias: torch.Size([2])
heads.object.task_heads.5.height.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.height.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.height.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.height.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.height.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.height.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.height.1.weight: torch.Size([1, 64, 3, 3])
heads.object.task_heads.5.height.1.bias: torch.Size([1])
heads.object.task_heads.5.dim.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.dim.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.dim.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.dim.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.dim.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.dim.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.dim.1.weight: torch.Size([3, 64, 3, 3])
heads.object.task_heads.5.dim.1.bias: torch.Size([3])
heads.object.task_heads.5.rot.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.rot.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.rot.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.rot.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.rot.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.rot.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.rot.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.5.rot.1.bias: torch.Size([2])
heads.object.task_heads.5.vel.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.vel.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.vel.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.vel.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.vel.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.vel.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.vel.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.5.vel.1.bias: torch.Size([2])
heads.object.task_heads.5.heatmap.0.conv.weight: torch.Size([64, 64, 3, 3])
heads.object.task_heads.5.heatmap.0.bn.weight: torch.Size([64])
heads.object.task_heads.5.heatmap.0.bn.bias: torch.Size([64])
heads.object.task_heads.5.heatmap.0.bn.running_mean: torch.Size([64])
heads.object.task_heads.5.heatmap.0.bn.running_var: torch.Size([64])
heads.object.task_heads.5.heatmap.0.bn.num_batches_tracked: torch.Size([])
heads.object.task_heads.5.heatmap.1.weight: torch.Size([2, 64, 3, 3])
heads.object.task_heads.5.heatmap.1.bias: torch.Size([2])
(BEVFusion_v4_torch1.13.0_cu116) mingyuan@rss-ai-dev-suz-kjc-gpu01-a100:/data2/xmy/01_project/bevfusion_mit_xmy_1205$ 
(BEVFusion_v4_torch1.13.0_cu116) mingyuan@rss-ai-dev-suz-kjc-gpu01-a100:/data2/xmy/01_project/bevfusion_mit_xmy_1205$ # 或者查看整个结构
(BEVFusion_v4_torch1.13.0_cu116) mingyuan@rss-ai-dev-suz-kjc-gpu01-a100:/data2/xmy/01_project/bevfusion_mit_xmy_1205$ python -c "
> import torch
> ckpt = torch.load('pretrained/camera-only-det.pth')
> state_dict = ckpt['state_dict']
> 
> # 按模块分组查看
> modules = {}
> for key in state_dict.keys():
>     # 按第一个点分割
>     if '.' in key:
>         module = key.split('.')[0]
>         if module not in modules:
>             modules[module] = []
>         modules[module].append(key)
> 
> print('=== 模块分组 ===')
> for module, keys in modules.items():
>     print(f'{module}: {len(keys)}个参数')
>     if len(keys) < 5:  # 小模块打印全部
>         for k in keys[:10]:
>             print(f'  {k}')
>     print()
> "
=== 模块分组 ===
encoders: 235个参数

decoder: 108个参数

heads: 294个参数
"""